    1  PRINT AT 5,5 ;"PLAY ANY MUSICAL INSTRUMENT"''' "1. HARMONIUM"''' "2. MANDOLIN "''' "3. MOUTH ORGAN"''' "A S D F G H J K ARE THE KEYS "
    2  INPUT  "TYPE IN YOUR CHOICE NOW "; I$
    3    IF CODE(I$)  < 49 OR CODE I$  >  51 THEN GOTO 2
    4  LET I=VAL(I$)
    5  DIM V$(3,14):REM FOR STORING ENVELOPES
    7  LET V$(1)="06T220" :REM HARMONIUM
    8  LET V$(2)="T240NUX1000W4" : REM MANDOLIN
    9  LET V$(3)="06T240UX300W7" : REM MOUTH ORGAN
   10  DIM W$(8,15):REM FOR STORING NOTES+ENVELOPES
   30  LET W$(1)=V$(I)+"C" : REM SA
   31  LET W$(2)=V$(I)+"D" : REM RE
   32  LET W$(3)=V$(I)+"E" : REM GA
   33  LET W$(4)=V$(I)+"F" : REM MA
   34  LET W$(5)=V$(I)+"G" : REM PA
   35  LET W$(6)=V$(I)+"A" : REM DHA
   36  LET W$(7)=V$(I)+"B" : REM NI
   37  LET W$(8)=V$(I)+"C" : REM SA OF NEXT SAPTAK
   40  LET A$=INKEY$:IF A$=" " THEN GOTO 40: REM SCANNING THE KEYBOARD
   45  IF A$="1" THEN LET I=1 : GOTO 40
   46  IF A$="2" THEN LET I=2 : GOTO 40
   47  IF A$="3" THEN LET I=3 : GOTO 40: REM ON-LINE INSTRUMENT SELECTION
   48  IF CODE(A$) < 97 THEN GOTO 40 : REM CRASH-PROOF
   50  GOTO CODE (A$) : REM JUMP ACCORDING TO ASCII ,SO DO'NT RENUMBER !
   97  PLAY W$(1) : GOTO 40 :REM KEY "A" = SA
  100  PLAY W$(3) : GOTO 40 :REM KEY "D" = GA
  102  PLAY W$(4) : GOTO 40 :REM KEY "F" = MA
  103  PLAY W$(5) : GOTO 40 :REM KEY "G" = PA
  104  PLAY W$(6) : GOTO 40 :REM KEY "H" = DHA
  106  PLAY W$(7) : GOTO 40 :REM KEY "J" = NI
  107  PLAY W$(8) : GOTO 40 :REM KEY "K" = SA OF NEXT SAPTAK
  115  PLAY W$(2) : GOTO 40 :REM KEY "S" = RE
  255  GOTO 40: REM CRASH-PROOF
